### ISSUE TITLE
关于ADRC的实际调参数应用。

### ISSUE THREAD

**Issue by KJsouth** [JcZou/matlab_quadsim#5]
你好，JcZou大神，我目前在研究飞行机械臂系统，打算采用ADRC进行飞机平台控制，请问你的那些ADRC的参数是如何整定的啊，有调试的方法吗？或是参考的论文。

**Comment by JcZou** [comment]
ADRC實際調參其實不難，LESO的參數只有一個，即觀測器帶寬wo，根據實際情況調節即可。外環的TD也很好調，根據實際跟蹤速度的要求調節。
所以主要調節的就是内環的控制器。内環可以直接使用已有的控制器，這樣就不需要做任何參數的調節。而如果使用NLSEF非綫性控制器作爲内環的話，實際調節的參數主要是三個，r1,c跟h1.  
 r1決定輸出的上限跟下限，c是damping factor，h1決定中間綫性區域的寬度。這些參數需要根據經驗來調節，實際中調節起來比PID更加容易

**Comment by KJsouth** [comment]
你在实际调试测试中，是位置环采用pid，姿态环LADRC吗？

**Comment by KJsouth** [comment]
目前我仿照px4里面的控制率，位置环是外环用p控制位置，pid控制速度。姿态环是外环用p控制角度，NLadrc控制角速度。你是怎么设计的啊？
