### ISSUE TITLE
关于函数adrc_cleso的意义。

### ISSUE THREAD

**Issue by KJsouth** [JcZou/matlab_quadsim#6]
hello，邹大神，关于matlab函数中adrc_cleso 的状态观测器，和普通leso不太一样，请问这个leso这么变形的意义是什么啊？有理论依据吗？多谢。

**Comment by KJsouth** [comment]
还有关于那个状态观测器2阶与三阶的选择有什么标准吗？

**Comment by JcZou** [comment]
cleso全称是cascade leso,是根据其它文献提出的一种新的方法来实现的。 一般观测器阶数越低越好，延时更低
