### ISSUE TITLE
关于姿态控制attitude_control。

### ISSUE THREAD

**Issue by KJsouth** [JcZou/matlab_quadsim#8]
大佬，这个姿态控制率和那个高度控制率不一样，高度控制率是采用普通的adrc，而姿态控制率却对 rad_err做TD,这是什么意思啊？问题有点多，辛苦大佬了。

**Comment by KJsouth** [comment]
请问大佬，你那里的参考论文可以分享一下吗。

**Comment by KJsouth** [comment]
td_controller和adrc_td的区别是什么啊？要是方便的话可以加个wechat聊吗？

**Comment by JcZou** [comment]
高度adrc和姿态adrc的结构不太一样  高度因为升力跟油门成二次关系，既bu^2 所以控制率要相应修改。 其它问题可以等我论文发表出来 上面对各个模块都有详细分析

**Comment by JcZou** [comment]
你可以加群:459133925

**Comment by KJsouth** [comment]
好的，多谢。请问您的论文什么时候发表出来啊？
